# Generated by Django 3.2.9 on 2021-11-19 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
