# Generated by Django 3.2.9 on 2021-11-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211120_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.TextField(default='wait for an answer'),
            preserve_default=False,
        ),
    ]
