# Generated by Django 3.2.9 on 2021-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211120_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.TextField(verbose_name=''),
        ),
    ]
