# Generated by Django 3.2.9 on 2021-11-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20211122_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.TextField(default='wait', help_text='для саппорта'),
            preserve_default=False,
        ),
    ]
