# Generated by Django 3.2.9 on 2021-11-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211122_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Решенные', 'Решенные'), ('Нерешенные', 'Нерешенные'), ('Замороженные', 'Замороженные')], default='Решенные', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.TextField(blank=True, help_text='для саппорта'),
        ),
    ]
