# Generated by Django 3.2.9 on 2021-11-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20211122_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Решенные', 'Решенные'), ('Нерешенные', 'Нерешенные'), ('Замороженные', 'Замороженные'), ('Ожидание ответа', 'Ожидание ответа')], default='Ожидание ответа', max_length=20),
        ),
    ]
