# Generated by Django 3.2.9 on 2021-12-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting for an answer', 'Waiting for an answer'), ('Resolved', 'Resolved'), ('Unresolved', 'Unresolved'), ('Frozen', 'Frozen')], default='Waiting for an answer', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.TextField(blank=True, help_text='For the support'),
        ),
    ]
