# Generated by Django 3.2.9 on 2021-12-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20211206_0042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choises',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Waiting for an answer', 'Waiting for an answer'), ('Resolved', 'Resolved'), ('Unresolved', 'Unresolved'), ('Frozen', 'Frozen')], default='Waiting for an answer', max_length=30),
        ),
    ]
