version: '2.1.1'
services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER:     ${POSTGRES_USR}
      - POSTGRES_PASSWORD: ${POSTGRES_PWD}
      - POSTGRES_DB:       ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data